INSERT INTO `racons`.`persona` (`nick`, `password`, `nombre`, `apellido1`, `apellido2`) VALUES ('FranProfe', '1234', 'Francisco', 'Muñoz', 'Martos');
INSERT INTO `racons`.`profesor` (`id_profesor`, `administrador`) VALUES ('2', '0');
INSERT INTO `racons`.`categoria` (`limite`, `nombre`) VALUES ('5', 'Matematicas');
INSERT INTO `racons`.`taller` (`nombre`, `descripcion`, `aforamiento`, `dia`, `hora_inicio`, `hora_fin`, `activo`, `id_profesor`, `id_categoria`) VALUES ('Taller', 'des', '50', '2', '800', '900', '0', '2', '1');
INSERT INTO `racons`.`categoria` (`limite`, `nombre`) VALUES ('5', 'Literatura');
INSERT INTO `racons`.`categoria` (`limite`, `nombre`) VALUES ('5', 'Musica');
INSERT INTO `racons`.`categoria` (`nombre`) VALUES ( 'Literatura');
INSERT INTO `racons`.`curso` (`curso`) VALUES ('1ºESO');
INSERT INTO `racons`.`curso` (`curso`) VALUES ('2ºESO');
INSERT INTO `racons`.`curso` (`curso`) VALUES ('3ºESO');
INSERT INTO `racons`.`curso` (`curso`) VALUES ('4ºESO');
INSERT INTO `racons`.`persona` (`nick`, `password`, `nombre`, `apellido1`, `apellido2`) VALUES ('alumno', 'alumno', 'Omar', 'Lopez', 'Garrido');
INSERT INTO `racons`.`persona` (`nick`, `password`, `nombre`, `apellido1`, `apellido2`) VALUES ('profesor', 'profesor', 'Alex', 'Sevillano', 'Barrera');
INSERT INTO `racons`.`persona` (`nick`, `password`, `nombre`, `apellido1`, `apellido2`) VALUES ('admin', 'admin', 'God', 'god', 'god');
INSERT INTO `racons`.`alumno` (`id_alumno`, `id_curso`) VALUES ('3', '4');
INSERT INTO `racons`.`profesor` (`id_profesor`, `administrador`) VALUES ('4', '0');
INSERT INTO `racons`.`profesor` (`id_profesor`, `administrador`) VALUES ('5', '1');
INSERT INTO `racons`.`persona` (`nick`, `password`, `nombre`, `apellido1`, `apellido2`) VALUES ('alumno1', 'alumno1', 'Migel', 'Fernandez', 'de la Vega');
INSERT INTO `racons`.`persona` (`nick`, `password`, `nombre`, `apellido1`, `apellido2`) VALUES ('alumno2', 'alumno2', 'Michael', 'Jackson', 'Negro');
INSERT INTO `racons`.`alumno` (`id_alumno`, `id_curso`) VALUES ('6', '4');
INSERT INTO `racons`.`alumno` (`id_alumno`, `id_curso`) VALUES ('7', '4');
INSERT INTO `racons`.`persona` (`nick`, `nombre`, `apellido1`, `apellido2`) VALUES ('alumno3', 'Mi ', 'Colega', 'el del Bigote');
INSERT INTO `racons`.`alumno` (`id_alumno`, `id_curso`) VALUES ('8', '4');
INSERT INTO `racons`.`taller` (`nombre`, `aforamiento`, `dia`, `hora_inicio`, `hora_fin`, `activo`, `id_profesor`, `id_categoria`) VALUES ('Integrame esta', '25', '3', '000800', '000900', '0', '2', '1');
INSERT INTO `racons`.`taller` (`nombre`, `descripcion`, `aforamiento`, `dia`, `hora_inicio`, `hora_fin`, `activo`, `id_profesor`, `id_categoria`) VALUES ('Tallerrrrr', 'Mateees', '25', '2', '800', '900', '0', '2', '1');
INSERT INTO `racons`.`taller` (`nombre`, `aforamiento`, `dia`, `hora_inicio`, `hora_fin`, `id_profesor`, `id_categoria`) VALUES ('Taller otro', '25', '2', '800', '1000', '2', '1');
INSERT INTO `racons`.`alumno_taller` (`id_alumno`, `id_taller`, `fecha`) VALUES ('8', '1', '2017-05-12');
INSERT INTO `racons`.`alumno_taller` (`id_alumno`, `id_taller`, `fecha`) VALUES ('8', '3', '2017-05-23');
INSERT INTO `racons`.`persona` (`nick`, `password`, `nombre`, `apellido1`, `apellido2`) VALUES ('admin@admin', 'admin', 'Jhon', 'Carter', 'Peliculon');
INSERT INTO `racons`.`profesor` (`id_profesor`, `administrador`) VALUES ('9', '1');
INSERT INTO `racons`.`curso_taller` (`id_curso`, `id_taller`) VALUES ('1', '1');
INSERT INTO `racons`.`curso_taller` (`id_curso`, `id_taller`) VALUES ('2', '3');
INSERT INTO `racons`.`curso_taller` (`id_curso`, `id_taller`) VALUES ('4', '4');
INSERT INTO `racons`.`curso_taller` (`id_curso`, `id_taller`) VALUES ('2', '1');
INSERT INTO `racons`.`curso_taller` (`id_curso`, `id_taller`) VALUES ('3', '2');
INSERT INTO `racons`.`curso_taller` (`id_curso`, `id_taller`) VALUES ('4', '3');
INSERT INTO `racons`.`curso_taller` (`id_curso`, `id_taller`) VALUES ('1', '4');
INSERT INTO `racons`.`curso_taller` (`id_curso`, `id_taller`) VALUES ('3', '1');
INSERT INTO `racons`.`curso_taller` (`id_curso`, `id_taller`) VALUES ('4', '2');
INSERT INTO `racons`.`curso_taller` (`id_curso`, `id_taller`) VALUES ('1', '3');
INSERT INTO `racons`.`curso_taller` (`id_curso`, `id_taller`) VALUES ('2', '4');
INSERT INTO `racons`.`alumno_taller` (`id_alumno`, `id_taller`, `fecha`) VALUES ('3', '2', '2017-06-15');
INSERT INTO `racons`.`alumno_taller` (`id_alumno`, `id_taller`, `fecha`) VALUES ('3', '1', '2017-06-2');
INSERT INTO `racons`.`persona` (`nick`, `password`, `nombre`, `apellido1`, `apellido2`) VALUES ('alumno@alumno', 'alumno', 'Jhon ', 'Salchi ', 'Jhon');
INSERT INTO `racons`.`alumno` (`id_alumno`, `id_curso`) VALUES ('10', '4');
INSERT INTO `racons`.`curso_taller` (`id_curso`, `id_taller`) VALUES ('3', '3');
UPDATE `racons`.`persona` SET `nick`='alumno@alumno' WHERE `id_persona`='3';
